### ISSUE TITLE
[FEATURE] Factory-Pattern  als (neues) Thema in VL

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/Lecture#44]
Das Factory-Pattern würde sich perfekt für die Erzeugung von Monstern eignen.
Die `MonsterFactory` schaut sich an, welches Design aktuell verwendet wird und wie weit fortgeschritten der Spieler ist (je weiter, desto stärker die Monster) und schmeißt dann die entsprechenden Monster raus.

Ich hab keinen aktuellen Plan zur Hand, daher weiß ich nicht, ob und wann das Pattern Bestandteil der Vorlesung ist. Am alten Praktikum orientiert, wäre Blatt 02 das Blatt mit den Monstern.

**Comment by cagix** [comment]
danke für den hinweis. bin nicht 100% sicher, aber ich glaube, das thema ist in der vl schon drin. ich lasse das ticket als erinnerung erstmal offen.

**Comment by cagix** [comment]
hmmmja, das ist als Factory-Method-Pattern schon dabei, allerdings nicht als reine Factory

**Comment by cagix** [comment]
@AMatutat Hier ist mal eine erste Aufstellung der aktuellen Themen einschließlich der bereits berücksichtigten neuen Themen. Fällt Dir noch was ein, was aus Deiner Sicht da noch mit rein sollte?

Eine erste Zeitabschätzung ist auch dabei. Die passt aber nicht überall (oft sind die Videos doch länger als die geplante Dauer), d.h. da müssten teilweise Videos/VL noch gestrafft werden oder noch weiter unterteilt werden. 

Eine Reihenfolge soll durch die Gliederung der Tabelle nicht angedeutet werden.

In Summe dürfen wir auf max. 30h Vorlesung kommen, in der Praxis werden wir mit 13x 90' = 20h die Grenze erreichen (wir sind ja nur ca. 13..14 Wochen online).

Thema | Einheit | Dauer: 18,5h | Neu
-- | -- | -- | --
Orga | Orga | 40 |  
Orga | Rückblick | 20 |  
Orga | Prüfungsvorbereitung | 20 |  
  |   |   |  
Git | Git1: Intro | 25 |  
Git | Git2: Basics | 30 |  
Git | Git3: Branches | 30 |  
Git | Git4: Brachingstrategien | 25 |  
Git | Git5: Remote | 30 |  
Git | Git6: Workflows | 25 |  
Git | Git7: Bisect | 10 |  
  |   |   |  
Pattern | Factory- (Method-) Pattern | 25 |  
Pattern | Visitor-Pattern | 15 |  
Pattern | Observer-Pattern | 15 |  
Pattern | Strategy-Pattern | 15 |  
Pattern | Template-Method-Pattern | 15 | x
  |   |   |  
Methods | Logging | 15 |  
Methods | Debugging | 15 | x
  |   |   |  
Testing | JUnit1: Basics | 30 |  
Testing | JUnit2: Testfall-Ermittlung | 30 |  
Testing | Mockito: Mocking | 20 | x
  |   |   |  
Clean Code | Javadoc | 10 | x
Clean Code | Bad Smells / Metrics | 35 |  
Clean Code | Refactoring | 35 |  
  |   |   |  
Generics | Generics1: Klassen & Methoden | 25 |  
Generics | Generics2: Bounds & Wildcards | 20 |  
Generics | Generics3: Type Erasure | 20 |  
Generics | Generics4: Polymorphie | 15 |  
  |   |   |  
Modern Java | Defaultmethoden | 20 |  
Modern Java | Funktionsinterfaces & Lambdas | 10 |  
Modern Java | Methodenreferenzen | 25 |  
Modern Java | Stream API | 30 | x
Modern Java | Records-Klassen | 20 | x
Modern Java | Optional | 20 | x
  |   |   |  
Misc | RegExp | 35 |  
Misc | Configuration & Packaging Tool | 25 | x
Misc | Enumerationen | 20 |  
Misc | Annotationen (+Lombok??) | 30 |  
Misc | Reflection | 30 |  
Misc | Serialisierung | 20 | x
  |   |   |  
GUI | Swing | 20 |  
GUI | Java2D | 20 |  
  |   |   |  
Build | Build1: ANT | 30 |  
Build | Build2: Maven | 20 |  
Build | Build3: Gradle | 15 |  
Build | Build4: CI | 20 |  
Build | Build5: Docker | 20 |  
  |   |   |  
Concurrency | Threads1: Intro | 10 |  
Concurrency | Threads2: Synchronisierung | 25 |  
Concurrency | Threads3: High-Level Konzepte | 15 |  
  |   |   |  
Database | JDBC | 20 | x
  |   |   |

**Comment by AMatutat** [comment]
ist "Buld5: Docker" nicht auch neu?
Auf anhieb sehe ich nix, was mir fehlen würde.

**Comment by cagix** [comment]
> ist "Buld5: Docker" nicht auch neu?
> 
> Auf anhieb sehe ich nix, was mir fehlen würde.
> 
> 

hmmm, im plan vom
letzten semester war es zumindest schon drin.

**Comment by Tobias321** [comment]
Sieht gut (und lang) aus, ich sehe auf Anhieb auch nix Fehlendes...

**Comment by cagix** [comment]
so, habe mal die Wiki-Seite https://github.com/PM-Dungeon/Lecture/wiki/Themen dafür angelegt ... 

damit brauchen wir das Ticket eigentlich nicht mehr, oder?
